### ISSUE TITLE
Fix error estimation

### ISSUE THREAD

**Issue by TCLamnidis** [TCLamnidis/RAStools#4]
Currently RASCal outputs errors as the standard deviation of the jackknife distribution `sqrt(sigma2)`. This should be changed to the SE of the mean `sqrt(sigma2)/sqrt(numBlocks)`

**Comment by stschiff** [comment]
Careful here... I think if the set of values you're computing `sigma2` from is actually the set of minus-one-blocks, then this doesn't seem right. The `sqrt(numBlocks)` thing only applies if you estimate the standard-deviation from the set of blocks themselves, as opposed to the minus-one-block sets.

**Comment by TCLamnidis** [comment]
You are correct, the current implementation already takes care of the normalisation.
